{
    parserClass="edu.clemson.resolve.plugin.parser.RESOLVEParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="RESOLVE"
    psiImplClassSuffix="Impl"
    psiPackage="edu.clemson.resolve.plugin.psi"
    psiImplPackage="edu.clemson.resolve.plugin.psi.impl"
    elementTypeHolderClass="edu.clemson.resolve.plugin.psi.RESOLVETypes"
    elementTypeClass="edu.clemson.resolve.plugin.psi.RESOLVEElementType"
    tokenTypeClass="edu.clemson.resolve.plugin.psi.RESOLVETokenType"

    tokens = [
        //space='regexp:\s+'
        SEMI=';'
        COMMA=','
        COLON=':'
        PRECIS='Precis'
        DEFINITION='Definition'
        END='end';
        USES='uses';

        comment='regexp:--.*'
        number='regexp:\d+(\.\d*)?'
        id='regexp:\p{Alpha}\w*'
        string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
    ]
}

module ::= precisModule

precisModule ::= PRECIS id SEMI
                 (usesList)?
                 END id SEMI

usesList ::= USES id (COMMA id)* SEMI
